/*
  Declarations for the Emscripten NNUE blob generated by
  emscripten/misc/embedded_nnue.js.
*/

#ifndef EMSCRIPTEN_EMBEDDED_NNUE_H_INCLUDED
#define EMSCRIPTEN_EMBEDDED_NNUE_H_INCLUDED

extern const char* gEmbeddedNNUEData;
extern const int   gEmbeddedNNUESize;

#endif
