
var Stockfish = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


null;var d;d||(d=typeof Stockfish !== 'undefined' ? Stockfish : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});d.postCustomMessage=a=>{const b=globalThis.PThread;if(b&&b.ic)for(let c of b.ic)c.postMessage({cmd:"custom",userData:a});else d.queue.put(a)};class ca{constructor(){this.ja=null;this.fa=[]}async get(){return 0<this.fa.length?this.fa.shift():await new Promise(a=>this.ja=a)}put(a){this.ja?(this.ja(a),this.ja=null):this.fa.push(a)}}d.queue=new ca;d.onCustomMessage=a=>{d.queue.put(a)};
d.postMessage=d.postCustomMessage;const h=[];d.addMessageListener=a=>{h.push(a)};d.removeMessageListener=a=>{a=h.indexOf(a);0<=a&&h.splice(a,1)};d.print=d.printErr=a=>{if(0===h.length)console.log(a);else for(let b of h)b(a)};d.terminate=()=>{const a=globalThis.PThread;a&&"function"===typeof a.lc&&a.lc()};var q={},u;for(u in d)d.hasOwnProperty(u)&&(q[u]=d[u]);var da=[],ea="./this.program";function fa(a,b){throw b;}
var ha="object"===typeof window,x="function"===typeof importScripts,ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,y="",ja,ka,la,A,D;
if(ia)y=x?require("path").dirname(y)+"/":__dirname+"/",ja=function(a,b){A||(A=require("fs"));D||(D=require("path"));a=D.normalize(a);return A.readFileSync(a,b?null:"utf8")},la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ka=function(a,b,c){A||(A=require("fs"));D||(D=require("path"));a=D.normalize(a);A.readFile(a,function(e,f){e?c(e):b(f.buffer)})},1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/")),da=process.argv.slice(2),process.on("uncaughtException",
function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",E),fa=function(a,b){if(noExitRuntime||0<na)throw process.exitCode=a,b;process.exit(a)},d.inspect=function(){return"[Emscripten Module object]"};else if(ha||x)x?y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,y.lastIndexOf("/")+1):y="",ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);
return b.responseText},x&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var oa=d.print||console.log.bind(console),F=d.printErr||console.warn.bind(console);for(u in q)q.hasOwnProperty(u)&&(d[u]=q[u]);q=null;
d.arguments&&(da=d.arguments);d.thisProgram&&(ea=d.thisProgram);d.quit&&(fa=d.quit);var pa;d.wasmBinary&&(pa=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!0;"object"!==typeof WebAssembly&&E("no native wasm support detected");var qa,G=!1;function assert(a,b){a||E("Assertion failed: "+b)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function I(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function sa(a){return a?I(J,a,void 0):""}
function ta(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function ua(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function va(a){var b=ua(a)+1,c=wa(b);ta(a,K,c,b);return c}var xa,K,J,ya,L;
function za(){var a=qa.buffer;xa=a;d.HEAP8=K=new Int8Array(a);d.HEAP16=ya=new Int16Array(a);d.HEAP32=L=new Int32Array(a);d.HEAPU8=J=new Uint8Array(a);d.HEAPU16=new Uint16Array(a);d.HEAPU32=new Uint32Array(a);d.HEAPF32=new Float32Array(a);d.HEAPF64=new Float64Array(a)}var Aa=[],Ba=[],Ca=[],Da=[],na=0;function Ea(){var a=d.preRun.shift();Aa.unshift(a)}var M=0,Fa=null,Ga=null;function Ha(){M++;d.monitorRunDependencies&&d.monitorRunDependencies(M)}
function Ia(){M--;d.monitorRunDependencies&&d.monitorRunDependencies(M);if(0==M&&(null!==Fa&&(clearInterval(Fa),Fa=null),Ga)){var a=Ga;Ga=null;a()}}d.preloadedImages={};d.preloadedAudios={};function E(a){if(d.onAbort)d.onAbort(a);F(a);G=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ja(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="stockfish.wasm";if(!Ja()){var Ka=N;N=d.locateFile?d.locateFile(Ka,y):y+Ka}
function La(){var a=N;try{if(a==N&&pa)return new Uint8Array(pa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){E(b)}}function Ma(){return pa||!ha&&!x||"function"!==typeof fetch?Promise.resolve().then(function(){return La()}):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return La()})}var O,P;
function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.ob;"number"===typeof c?void 0===b.La?dynCall_v.call(null,c):dynCall_vi.apply(null,[c,b.La]):c(void 0===b.La?null:b.La)}}}function Oa(a,b){for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Pa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Oa(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Qa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Q(a){if("/"===a)return"/";a=Pa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function R(a,b){return Pa(a+"/"+b)}function Ra(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){E("randomDevice")}}
function S(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:T.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Oa(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function Sa(a,b){function c(l){for(var n=0;n<l.length&&""===l[n];n++);for(var p=l.length-1;0<=p&&""===l[p];p--);return n>p?[]:l.slice(n,p-n+1)}a=S(a).substr(1);b=S(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}var Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],ra:b};T.bb(a,Va)}
var Va={open:function(a){var b=Ta[a.node.rdev];if(!b)throw new T.L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ra.flush(a.tty)},flush:function(a){a.tty.ra.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.ra.qb)throw new T.L(60);for(var f=0,g=0;g<e;g++){try{var l=a.tty.ra.qb(a.tty)}catch(n){throw new T.L(29);}if(void 0===l&&0===f)throw new T.L(6);if(null===l||void 0===l)break;f++;b[c+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.ra.Za)throw new T.L(60);
try{for(var f=0;f<e;f++)a.tty.ra.Za(a.tty,b[c+f])}catch(g){throw new T.L(29);}e&&(a.node.timestamp=Date.now());return f}},Xa={qb:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.alloc(256),e=0;try{e=A.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Wa(b,!0)}return a.input.shift()},Za:function(a,b){null===b||10===b?(oa(I(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(oa(I(a.output,0)),a.output=[])}},Ya={Za:function(a,b){null===b||10===b?(F(I(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(F(I(a.output,0)),a.output=[])}},U={ba:null,S:function(){return U.createNode(null,"/",16895,0)},
createNode:function(a,b,c,e){if(T.Tb(c)||T.isFIFO(c))throw new T.L(63);U.ba||(U.ba={dir:{node:{Z:U.M.Z,W:U.M.W,lookup:U.M.lookup,ea:U.M.ea,rename:U.M.rename,unlink:U.M.unlink,rmdir:U.M.rmdir,readdir:U.M.readdir,symlink:U.M.symlink},stream:{$:U.O.$}},file:{node:{Z:U.M.Z,W:U.M.W},stream:{$:U.O.$,read:U.O.read,write:U.O.write,ua:U.O.ua,pa:U.O.pa,qa:U.O.qa}},link:{node:{Z:U.M.Z,W:U.M.W,readlink:U.M.readlink},stream:{}},gb:{node:{Z:U.M.Z,W:U.M.W},stream:T.Hb}});c=T.createNode(a,b,c,e);T.T(c.mode)?(c.M=
U.ba.dir.node,c.O=U.ba.dir.stream,c.N={}):T.isFile(c.mode)?(c.M=U.ba.file.node,c.O=U.ba.file.stream,c.R=0,c.N=null):T.oa(c.mode)?(c.M=U.ba.link.node,c.O=U.ba.link.stream):T.Aa(c.mode)&&(c.M=U.ba.gb.node,c.O=U.ba.gb.stream);c.timestamp=Date.now();a&&(a.N[b]=c,a.timestamp=c.timestamp);return c},wc:function(a){return a.N?a.N.subarray?a.N.subarray(0,a.R):new Uint8Array(a.N):new Uint8Array(0)},lb:function(a,b){var c=a.N?a.N.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),
c=a.N,a.N=new Uint8Array(b),0<a.R&&a.N.set(c.subarray(0,a.R),0))},hc:function(a,b){if(a.R!=b)if(0==b)a.N=null,a.R=0;else{var c=a.N;a.N=new Uint8Array(b);c&&a.N.set(c.subarray(0,Math.min(b,a.R)));a.R=b}},M:{Z:function(a){var b={};b.dev=T.Aa(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;T.T(a.mode)?b.size=4096:T.isFile(a.mode)?b.size=a.R:T.oa(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);
b.Fb=4096;b.blocks=Math.ceil(b.size/b.Fb);return b},W:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&U.hc(a,b.size)},lookup:function(){throw T.Oa[44];},ea:function(a,b,c,e){return U.createNode(a,b,c,e)},rename:function(a,b,c){if(T.T(a.mode)){try{var e=T.da(b,c)}catch(g){}if(e)for(var f in e.N)throw new T.L(55);}delete a.parent.N[a.name];a.parent.timestamp=Date.now();a.name=c;b.N[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,
b){delete a.N[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=T.da(a,b),e;for(e in c.N)throw new T.L(55);delete a.N[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.N)a.N.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!T.oa(a.mode))throw new T.L(28);return a.link}},O:{read:function(a,b,c,e,f){var g=a.node.N;if(f>=a.node.R)return 0;a=Math.min(a.node.R-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,
f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write:function(a,b,c,e,f,g){b.buffer===K.buffer&&(g=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.N||a.N.subarray)){if(g)return a.N=b.subarray(c,c+e),a.R=e;if(0===a.R&&0===f)return a.N=b.slice(c,c+e),a.R=e;if(f+e<=a.R)return a.N.set(b.subarray(c,c+e),f),e}U.lb(a,f+e);if(a.N.subarray&&b.subarray)a.N.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.N[f+g]=b[c+g];a.R=Math.max(a.R,f+e);return e},$:function(a,b,c){1===c?b+=a.position:
2===c&&T.isFile(a.node.mode)&&(b+=a.node.R);if(0>b)throw new T.L(28);return b},ua:function(a,b,c){U.lb(a.node,b+c);a.node.R=Math.max(a.node.R,b+c)},pa:function(a,b,c,e,f,g){if(0!==b)throw new T.L(28);if(!T.isFile(a.node.mode))throw new T.L(43);a=a.node.N;if(g&2||a.buffer!==xa){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;E();c=void 0;if(!c)throw new T.L(48);K.set(a,c)}else e=!1,c=a.byteOffset;return{fc:c,Ja:e}},qa:function(a,b,c,e,f){if(!T.isFile(a.node.mode))throw new T.L(43);
if(f&2)return 0;U.O.write(a,b,0,e,c,!1);return 0}}};function Za(a,b,c){var e="al "+a;ka(a,function(f){assert(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&Ia()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Ha()}
var T={root:null,ya:[],jb:{},streams:[],$b:1,aa:null,ib:"/",Sa:!1,tb:!0,U:{},xb:{vb:{Bb:1,Cb:2}},L:null,Oa:{},Qb:null,Ea:0,P:function(a,b){a=S(T.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={Na:!0,ab:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.ab)throw new T.L(32);a=Oa(a.split("/").filter(function(l){return!!l}),!1);var f=T.root;c="/";for(e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;f=T.da(f,a[e]);c=R(c,a[e]);T.ka(f)&&(!g||g&&b.Na)&&(f=f.xa.root);if(!g||b.Y)for(g=
0;T.oa(f.mode);)if(f=T.readlink(c),c=S(Qa(c),f),f=T.P(c,{ab:b.ab}).node,40<g++)throw new T.L(32);}return{path:c,node:f}},ha:function(a){for(var b;;){if(T.Ba(a))return a=a.S.ub,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ra:function(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%T.aa.length},rb:function(a){var b=T.Ra(a.parent.id,a.name);a.ma=T.aa[b];T.aa[b]=a},sb:function(a){var b=T.Ra(a.parent.id,a.name);if(T.aa[b]===a)T.aa[b]=a.ma;else for(b=
T.aa[b];b;){if(b.ma===a){b.ma=a.ma;break}b=b.ma}},da:function(a,b){var c=T.Xb(a);if(c)throw new T.L(c,a);for(c=T.aa[T.Ra(a.id,b)];c;c=c.ma){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return T.lookup(a,b)},createNode:function(a,b,c,e){a=new T.yb(a,b,c,e);T.rb(a);return a},Ma:function(a){T.sb(a)},Ba:function(a){return a===a.parent},ka:function(a){return!!a.xa},isFile:function(a){return 32768===(a&61440)},T:function(a){return 16384===(a&61440)},oa:function(a){return 40960===(a&61440)},Aa:function(a){return 8192===
(a&61440)},Tb:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Rb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Zb:function(a){var b=T.Rb[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},mb:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},na:function(a,b){if(T.tb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;
return 0},Xb:function(a){var b=T.na(a,"x");return b?b:a.M.lookup?0:2},Ya:function(a,b){try{return T.da(a,b),20}catch(c){}return T.na(a,"wx")},Ca:function(a,b,c){try{var e=T.da(a,b)}catch(f){return f.V}if(a=T.na(a,"wx"))return a;if(c){if(!T.T(e.mode))return 54;if(T.Ba(e)||T.ha(e)===T.cwd())return 10}else if(T.T(e.mode))return 31;return 0},Yb:function(a,b){return a?T.oa(a.mode)?32:T.T(a.mode)&&("r"!==T.mb(b)||b&512)?31:T.na(a,T.mb(b)):44},Ab:4096,ac:function(a,b){b=b||T.Ab;for(a=a||0;a<=b;a++)if(!T.streams[a])return a;
throw new T.L(33);},ia:function(a){return T.streams[a]},Ob:function(a,b,c){T.Ia||(T.Ia=function(){},T.Ia.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var e=new T.Ia,f;for(f in a)e[f]=a[f];a=e;b=T.ac(b,c);a.fd=b;return T.streams[b]=a},Ib:function(a){T.streams[a]=null},Hb:{open:function(a){a.O=T.Sb(a.node.rdev).O;a.O.open&&a.O.open(a)},$:function(){throw new T.L(70);}},Xa:function(a){return a>>8},yc:function(a){return a&255},la:function(a,b){return a<<8|b},bb:function(a,
b){T.jb[a]={O:b}},Sb:function(a){return T.jb[a]},pb:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.ya)}return b},wb:function(a,b){function c(l){T.Ea--;return b(l)}function e(l){if(l){if(!e.Pb)return e.Pb=!0,c(l)}else++g>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);T.Ea++;1<T.Ea&&F("warning: "+T.Ea+" FS.syncfs operations in flight at once, probably just doing extra work");var f=T.pb(T.root.S),g=0;f.forEach(function(l){if(!l.type.wb)return e(null);l.type.wb(l,
a,e)})},S:function(a,b,c){var e="/"===c,f=!c;if(e&&T.root)throw new T.L(10);if(!e&&!f){var g=T.P(c,{Na:!1});c=g.path;g=g.node;if(T.ka(g))throw new T.L(10);if(!T.T(g.mode))throw new T.L(54);}b={type:a,Bc:b,ub:c,ya:[]};a=a.S(b);a.S=b;b.root=a;e?T.root=a:g&&(g.xa=b,g.S&&g.S.ya.push(b));return a},Gc:function(a){a=T.P(a,{Na:!1});if(!T.ka(a.node))throw new T.L(28);a=a.node;var b=a.xa,c=T.pb(b);Object.keys(T.aa).forEach(function(e){for(e=T.aa[e];e;){var f=e.ma;c.includes(e.S)&&T.Ma(e);e=f}});a.xa=null;a.S.ya.splice(a.S.ya.indexOf(b),
1)},lookup:function(a,b){return a.M.lookup(a,b)},ea:function(a,b,c){var e=T.P(a,{parent:!0}).node;a=Q(a);if(!a||"."===a||".."===a)throw new T.L(28);var f=T.Ya(e,a);if(f)throw new T.L(f);if(!e.M.ea)throw new T.L(63);return e.M.ea(e,a,b,c)},create:function(a,b){return T.ea(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return T.ea(a,(void 0!==b?b:511)&1023|16384,0)},zc:function(a,b){a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{T.mkdir(c,b)}catch(f){if(20!=f.V)throw f;
}}},Da:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return T.ea(a,b|8192,c)},symlink:function(a,b){if(!S(a))throw new T.L(44);var c=T.P(b,{parent:!0}).node;if(!c)throw new T.L(44);b=Q(b);var e=T.Ya(c,b);if(e)throw new T.L(e);if(!c.M.symlink)throw new T.L(63);return c.M.symlink(c,b,a)},rename:function(a,b){var c=Qa(a),e=Qa(b),f=Q(a),g=Q(b);var l=T.P(a,{parent:!0});var n=l.node;l=T.P(b,{parent:!0});l=l.node;if(!n||!l)throw new T.L(44);if(n.S!==l.S)throw new T.L(75);var p=T.da(n,f);e=Sa(a,e);
if("."!==e.charAt(0))throw new T.L(28);e=Sa(b,c);if("."!==e.charAt(0))throw new T.L(55);try{var m=T.da(l,g)}catch(r){}if(p!==m){c=T.T(p.mode);if(f=T.Ca(n,f,c))throw new T.L(f);if(f=m?T.Ca(l,g,c):T.Ya(l,g))throw new T.L(f);if(!n.M.rename)throw new T.L(63);if(T.ka(p)||m&&T.ka(m))throw new T.L(10);if(l!==n&&(f=T.na(n,"w")))throw new T.L(f);try{T.U.willMovePath&&T.U.willMovePath(a,b)}catch(r){F("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}T.sb(p);try{n.M.rename(p,
l,g)}catch(r){throw r;}finally{T.rb(p)}try{if(T.U.onMovePath)T.U.onMovePath(a,b)}catch(r){F("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+r.message)}}},rmdir:function(a){var b=T.P(a,{parent:!0}).node,c=Q(a),e=T.da(b,c),f=T.Ca(b,c,!0);if(f)throw new T.L(f);if(!b.M.rmdir)throw new T.L(63);if(T.ka(e))throw new T.L(10);try{T.U.willDeletePath&&T.U.willDeletePath(a)}catch(g){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.M.rmdir(b,c);T.Ma(e);
try{if(T.U.onDeletePath)T.U.onDeletePath(a)}catch(g){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readdir:function(a){a=T.P(a,{Y:!0}).node;if(!a.M.readdir)throw new T.L(54);return a.M.readdir(a)},unlink:function(a){var b=T.P(a,{parent:!0}).node,c=Q(a),e=T.da(b,c),f=T.Ca(b,c,!1);if(f)throw new T.L(f);if(!b.M.unlink)throw new T.L(63);if(T.ka(e))throw new T.L(10);try{T.U.willDeletePath&&T.U.willDeletePath(a)}catch(g){F("FS.trackingDelegate['willDeletePath']('"+a+
"') threw an exception: "+g.message)}b.M.unlink(b,c);T.Ma(e);try{if(T.U.onDeletePath)T.U.onDeletePath(a)}catch(g){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readlink:function(a){a=T.P(a).node;if(!a)throw new T.L(44);if(!a.M.readlink)throw new T.L(28);return S(T.ha(a.parent),a.M.readlink(a))},stat:function(a,b){a=T.P(a,{Y:!b}).node;if(!a)throw new T.L(44);if(!a.M.Z)throw new T.L(63);return a.M.Z(a)},lstat:function(a){return T.stat(a,!0)},chmod:function(a,b,c){a=
"string"===typeof a?T.P(a,{Y:!c}).node:a;if(!a.M.W)throw new T.L(63);a.M.W(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){T.chmod(a,b,!0)},fchmod:function(a,b){a=T.ia(a);if(!a)throw new T.L(8);T.chmod(a.node,b)},chown:function(a,b,c,e){a="string"===typeof a?T.P(a,{Y:!e}).node:a;if(!a.M.W)throw new T.L(63);a.M.W(a,{timestamp:Date.now()})},lchown:function(a,b,c){T.chown(a,b,c,!0)},fchown:function(a,b,c){a=T.ia(a);if(!a)throw new T.L(8);T.chown(a.node,b,c)},truncate:function(a,
b){if(0>b)throw new T.L(28);a="string"===typeof a?T.P(a,{Y:!0}).node:a;if(!a.M.W)throw new T.L(63);if(T.T(a.mode))throw new T.L(31);if(!T.isFile(a.mode))throw new T.L(28);var c=T.na(a,"w");if(c)throw new T.L(c);a.M.W(a,{size:b,timestamp:Date.now()})},vc:function(a,b){a=T.ia(a);if(!a)throw new T.L(8);if(0===(a.flags&2097155))throw new T.L(28);T.truncate(a.node,b)},Hc:function(a,b,c){a=T.P(a,{Y:!0}).node;a.M.W(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,e,f){if(""===a)throw new T.L(44);b="string"===
typeof b?T.Zb(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Pa(a);try{g=T.P(a,{Y:!(b&131072)}).node}catch(n){}}var l=!1;if(b&64)if(g){if(b&128)throw new T.L(20);}else g=T.ea(a,c,0),l=!0;if(!g)throw new T.L(44);T.Aa(g.mode)&&(b&=-513);if(b&65536&&!T.T(g.mode))throw new T.L(54);if(!l&&(c=T.Yb(g,b)))throw new T.L(c);b&512&&T.truncate(g,0);b&=-131713;e=T.Ob({node:g,path:T.ha(g),flags:b,seekable:!0,position:0,O:g.O,qc:[],error:!1},e,f);e.O.open&&e.O.open(e);
!d.logReadFiles||b&1||(T.$a||(T.$a={}),a in T.$a||(T.$a[a]=1,F("FS.trackingDelegate error on read file: "+a)));try{T.U.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=T.xb.vb.Bb),0!==(b&2097155)&&(f|=T.xb.vb.Cb),T.U.onOpenFile(a,f))}catch(n){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return e},close:function(a){if(T.wa(a))throw new T.L(8);a.Qa&&(a.Qa=null);try{a.O.close&&a.O.close(a)}catch(b){throw b;}finally{T.Ib(a.fd)}a.fd=null},wa:function(a){return null===a.fd},
$:function(a,b,c){if(T.wa(a))throw new T.L(8);if(!a.seekable||!a.O.$)throw new T.L(70);if(0!=c&&1!=c&&2!=c)throw new T.L(28);a.position=a.O.$(a,b,c);a.qc=[];return a.position},read:function(a,b,c,e,f){if(0>e||0>f)throw new T.L(28);if(T.wa(a))throw new T.L(8);if(1===(a.flags&2097155))throw new T.L(8);if(T.T(a.node.mode))throw new T.L(31);if(!a.O.read)throw new T.L(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new T.L(70);b=a.O.read(a,b,c,e,f);g||(a.position+=b);return b},
write:function(a,b,c,e,f,g){if(0>e||0>f)throw new T.L(28);if(T.wa(a))throw new T.L(8);if(0===(a.flags&2097155))throw new T.L(8);if(T.T(a.node.mode))throw new T.L(31);if(!a.O.write)throw new T.L(28);a.seekable&&a.flags&1024&&T.$(a,0,2);var l="undefined"!==typeof f;if(!l)f=a.position;else if(!a.seekable)throw new T.L(70);b=a.O.write(a,b,c,e,f,g);l||(a.position+=b);try{if(a.path&&T.U.onWriteToFile)T.U.onWriteToFile(a.path)}catch(n){F("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
n.message)}return b},ua:function(a,b,c){if(T.wa(a))throw new T.L(8);if(0>b||0>=c)throw new T.L(28);if(0===(a.flags&2097155))throw new T.L(8);if(!T.isFile(a.node.mode)&&!T.T(a.node.mode))throw new T.L(43);if(!a.O.ua)throw new T.L(138);a.O.ua(a,b,c)},pa:function(a,b,c,e,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new T.L(2);if(1===(a.flags&2097155))throw new T.L(2);if(!a.O.pa)throw new T.L(43);return a.O.pa(a,b,c,e,f,g)},qa:function(a,b,c,e,f){return a&&a.O.qa?a.O.qa(a,b,c,e,f):0},Ac:function(){return 0},
Ta:function(a,b,c){if(!a.O.Ta)throw new T.L(59);return a.O.Ta(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=T.open(a,b.flags);a=T.stat(a).size;var f=new Uint8Array(a);T.read(e,f,0,a,0);"utf8"===b.encoding?c=I(f,0):"binary"===b.encoding&&(c=f);T.close(e);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=T.open(a,c.flags,c.mode);if("string"===
typeof b){var e=new Uint8Array(ua(b)+1);b=ta(b,e,0,e.length);T.write(a,e,0,b,void 0,c.Gb)}else if(ArrayBuffer.isView(b))T.write(a,b,0,b.byteLength,void 0,c.Gb);else throw Error("Unsupported data type");T.close(a)},cwd:function(){return T.ib},chdir:function(a){a=T.P(a,{Y:!0});if(null===a.node)throw new T.L(44);if(!T.T(a.node.mode))throw new T.L(54);var b=T.na(a.node,"x");if(b)throw new T.L(b);T.ib=a.path},Kb:function(){T.mkdir("/tmp");T.mkdir("/home");T.mkdir("/home/web_user")},Jb:function(){T.mkdir("/dev");
T.bb(T.la(1,3),{read:function(){return 0},write:function(b,c,e,f){return f}});T.Da("/dev/null",T.la(1,3));Ua(T.la(5,0),Xa);Ua(T.la(6,0),Ya);T.Da("/dev/tty",T.la(5,0));T.Da("/dev/tty1",T.la(6,0));var a=Ra();T.ga("/dev","random",a);T.ga("/dev","urandom",a);T.mkdir("/dev/shm");T.mkdir("/dev/shm/tmp")},Mb:function(){T.mkdir("/proc");var a=T.mkdir("/proc/self");T.mkdir("/proc/self/fd");T.S({S:function(){var b=T.createNode(a,"fd",16895,73);b.M={lookup:function(c,e){var f=T.ia(+e);if(!f)throw new T.L(8);
c={parent:null,S:{ub:"fake"},M:{readlink:function(){return f.path}}};return c.parent=c}};return b}},{},"/proc/self/fd")},Nb:function(){d.stdin?T.ga("/dev","stdin",d.stdin):T.symlink("/dev/tty","/dev/stdin");d.stdout?T.ga("/dev","stdout",null,d.stdout):T.symlink("/dev/tty","/dev/stdout");d.stderr?T.ga("/dev","stderr",null,d.stderr):T.symlink("/dev/tty1","/dev/stderr");T.open("/dev/stdin",0);T.open("/dev/stdout",1);T.open("/dev/stderr",1)},kb:function(){T.L||(T.L=function(a,b){this.node=b;this.jc=function(c){this.V=
c};this.jc(a);this.message="FS error"},T.L.prototype=Error(),T.L.prototype.constructor=T.L,[44].forEach(function(a){T.Oa[a]=new T.L(a);T.Oa[a].stack="<generic error, no stack>"}))},kc:function(){T.kb();T.aa=Array(4096);T.S(U,{},"/");T.Kb();T.Jb();T.Mb();T.Qb={MEMFS:U}},va:function(a,b,c){T.va.Sa=!0;T.kb();d.stdin=a||d.stdin;d.stdout=b||d.stdout;d.stderr=c||d.stderr;T.Nb()},Cc:function(){T.va.Sa=!1;var a=d._fflush;a&&a(0);for(a=0;a<T.streams.length;a++){var b=T.streams[a];b&&T.close(b)}},Pa:function(a,
b){var c=0;a&&(c|=365);b&&(c|=146);return c},uc:function(a,b){a=T.Ka(a,b);return a.exists?a.object:null},Ka:function(a,b){try{var c=T.P(a,{Y:!b});a=c.path}catch(f){}var e={Ba:!1,exists:!1,error:0,name:null,path:null,object:null,bc:!1,dc:null,cc:null};try{c=T.P(a,{parent:!0}),e.bc=!0,e.dc=c.path,e.cc=c.node,e.name=Q(a),c=T.P(a,{Y:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.Ba="/"===c.path}catch(f){e.error=f.V}return e},sc:function(a,b){a="string"===typeof a?a:T.ha(a);for(b=
b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=R(a,c);try{T.mkdir(e)}catch(f){}a=e}}return e},Lb:function(a,b,c,e,f){a=R("string"===typeof a?a:T.ha(a),b);return T.create(a,T.Pa(e,f))},hb:function(a,b,c,e,f,g){a=b?R("string"===typeof a?a:T.ha(a),b):a;e=T.Pa(e,f);f=T.create(a,e);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var l=c.length;b<l;++b)a[b]=c.charCodeAt(b);c=a}T.chmod(f,e|146);a=T.open(f,577);T.write(a,c,0,c.length,0,g);T.close(a);T.chmod(f,e)}return f},ga:function(a,
b,c,e){a=R("string"===typeof a?a:T.ha(a),b);b=T.Pa(!!c,!!e);T.ga.Xa||(T.ga.Xa=64);var f=T.la(T.ga.Xa++,0);T.bb(f,{open:function(g){g.seekable=!1},close:function(){e&&e.buffer&&e.buffer.length&&e(10)},read:function(g,l,n,p){for(var m=0,r=0;r<p;r++){try{var w=c()}catch(z){throw new T.L(29);}if(void 0===w&&0===m)throw new T.L(6);if(null===w||void 0===w)break;m++;l[n+r]=w}m&&(g.node.timestamp=Date.now());return m},write:function(g,l,n,p){for(var m=0;m<p;m++)try{e(l[n+m])}catch(r){throw new T.L(29);}p&&
(g.node.timestamp=Date.now());return m}});return T.Da(a,b,f)},nb:function(a){if(a.Ua||a.Ub||a.link||a.N)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.N=Wa(ja(a.url),!0),a.R=a.N.length}catch(b){throw new T.L(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},
rc:function(a,b,c,e,f){function g(){this.Va=!1;this.fa=[]}g.prototype.get=function(m){if(!(m>this.length-1||0>m)){var r=m%this.chunkSize;return this.ja(m/this.chunkSize|0)[r]}};g.prototype.zb=function(m){this.ja=m};g.prototype.fb=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var r=Number(m.getResponseHeader("Content-length")),w,z=(w=m.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;m=(w=m.getResponseHeader("Content-Encoding"))&&"gzip"===w;var k=1048576;z||(k=r);var t=this;t.zb(function(v){var B=v*k,H=(v+1)*k-1;H=Math.min(H,r-1);if("undefined"===typeof t.fa[v]){var Bb=t.fa;if(B>H)throw Error("invalid range ("+B+", "+H+") or no bytes requested!");if(H>r-1)throw Error("only "+r+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);r!==k&&C.setRequestHeader("Range","bytes="+B+"-"+H);"undefined"!=typeof Uint8Array&&(C.responseType="arraybuffer");
C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);B=void 0!==C.response?new Uint8Array(C.response||[]):Wa(C.responseText||"",!0);Bb[v]=B}if("undefined"===typeof t.fa[v])throw Error("doXHR failed!");return t.fa[v]});if(m||!r)k=r=1,k=r=this.ja(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Eb=r;this.Db=k;this.Va=
!0};if("undefined"!==typeof XMLHttpRequest){if(!x)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new g;Object.defineProperties(l,{length:{get:function(){this.Va||this.fb();return this.Eb}},chunkSize:{get:function(){this.Va||this.fb();return this.Db}}});l={Ua:!1,N:l}}else l={Ua:!1,url:c};var n=T.Lb(a,b,l,e,f);l.N?n.N=l.N:l.url&&(n.N=null,n.url=l.url);Object.defineProperties(n,{R:{get:function(){return this.N.length}}});
var p={};Object.keys(n.O).forEach(function(m){var r=n.O[m];p[m]=function(){T.nb(n);return r.apply(null,arguments)}});p.read=function(m,r,w,z,k){T.nb(n);m=m.node.N;if(k>=m.length)return 0;z=Math.min(m.length-k,z);if(m.slice)for(var t=0;t<z;t++)r[w+t]=m[k+t];else for(t=0;t<z;t++)r[w+t]=m.get(k+t);return z};n.O=p;return n},tc:function(a,b,c,e,f,g,l,n,p,m){function r(z){function k(v){m&&m();n||T.hb(a,b,v,e,f,p);g&&g();Ia()}var t=!1;d.preloadPlugins.forEach(function(v){!t&&v.canHandle(w)&&(v.handle(z,
w,k,function(){l&&l();Ia()}),t=!0)});t||k(z)}V.va();var w=b?S(R(a,b)):a;Ha();"string"==typeof c?Za(c,function(z){r(z)},l):r(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},cb:function(){return"EM_FS_"+window.location.pathname},eb:20,ta:"FILE_DATA",Dc:function(a,b,c){b=b||function(){};c=c||function(){};var e=T.indexedDB();try{var f=e.open(T.cb(),T.eb)}catch(g){return c(g)}f.onupgradeneeded=function(){oa("creating db");f.result.createObjectStore(T.ta)};
f.onsuccess=function(){var g=f.result.transaction([T.ta],"readwrite"),l=g.objectStore(T.ta),n=0,p=0,m=a.length;a.forEach(function(r){r=l.put(T.Ka(r).object.N,r);r.onsuccess=function(){n++;n+p==m&&(0==p?b():c())};r.onerror=function(){p++;n+p==m&&(0==p?b():c())}});g.onerror=c};f.onerror=c},xc:function(a,b,c){b=b||function(){};c=c||function(){};var e=T.indexedDB();try{var f=e.open(T.cb(),T.eb)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var l=g.transaction([T.ta],
"readonly")}catch(w){c(w);return}var n=l.objectStore(T.ta),p=0,m=0,r=a.length;a.forEach(function(w){var z=n.get(w);z.onsuccess=function(){T.Ka(w).exists&&T.unlink(w);T.hb(Qa(w),Q(w),z.result,!0,!0,!0);p++;p+m==r&&(0==m?b():c())};z.onerror=function(){m++;p+m==r&&(0==m?b():c())}});l.onerror=c};f.onerror=c}},$a={};
function ab(a,b){var c=T.stat;try{var e=c(a)}catch(f){if(f&&f.node&&Pa(a)!==Pa(T.ha(f.node)))return-54;throw f;}L[b>>2]=e.dev;L[b+4>>2]=0;L[b+8>>2]=e.ino;L[b+12>>2]=e.mode;L[b+16>>2]=e.nlink;L[b+20>>2]=e.uid;L[b+24>>2]=e.gid;L[b+28>>2]=e.rdev;L[b+32>>2]=0;P=[e.size>>>0,(O=e.size,1<=+Math.abs(O)?0<O?(Math.min(+Math.floor(O/4294967296),4294967295)|0)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];L[b+40>>2]=P[0];L[b+44>>2]=P[1];L[b+48>>2]=4096;L[b+52>>2]=e.blocks;L[b+56>>2]=e.atime.getTime()/1E3|
0;L[b+60>>2]=0;L[b+64>>2]=e.mtime.getTime()/1E3|0;L[b+68>>2]=0;L[b+72>>2]=e.ctime.getTime()/1E3|0;L[b+76>>2]=0;P=[e.ino>>>0,(O=e.ino,1<=+Math.abs(O)?0<O?(Math.min(+Math.floor(O/4294967296),4294967295)|0)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];L[b+80>>2]=P[0];L[b+84>>2]=P[1];return 0}var bb=void 0;function W(){bb+=4;return L[bb-4>>2]}function X(a){a=T.ia(a);if(!a)throw new T.L(8);return a}var cb;cb=ia?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
var db={};function eb(){if(!fb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in db)void 0===db[b]?delete a[b]:a[b]=db[b];var c=[];for(b in a)c.push(b+"="+a[b]);fb=c}return fb}var fb;function gb(a){return 0===a%4&&(0!==a%100||0===a%400)}function hb(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}
var ib=[31,29,31,30,31,30,31,31,30,31,30,31],jb=[31,28,31,30,31,30,31,31,30,31,30,31];function kb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(gb(a.getFullYear())?ib:jb)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function lb(a,b,c,e){function f(k,t,v){for(k="number"===typeof k?k.toString():k||"";k.length<t;)k=v[0]+k;return k}function g(k,t){return f(k,t,"0")}function l(k,t){function v(H){return 0>H?-1:0<H?1:0}var B;0===(B=v(k.getFullYear()-t.getFullYear()))&&0===(B=v(k.getMonth()-t.getMonth()))&&(B=v(k.getDate()-t.getDate()));return B}function n(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function p(k){k=kb(new Date(k.X+1900,0,1),k.Ha);var t=new Date(k.getFullYear()+1,0,4),v=n(new Date(k.getFullYear(),0,4));t=n(t);return 0>=l(v,k)?0>=l(t,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var m=L[e+40>>2];e={oc:L[e>>2],nc:L[e+4>>2],Fa:L[e+8>>2],za:L[e+12>>2],sa:L[e+16>>2],X:L[e+20>>2],Ga:L[e+24>>2],Ha:L[e+28>>2],Ec:L[e+32>>2],mc:L[e+36>>
2],pc:m?sa(m):""};c=sa(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in m)c=c.replace(new RegExp(r,"g"),m[r]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
z="January February March April May June July August September October November December".split(" ");m={"%a":function(k){return w[k.Ga].substring(0,3)},"%A":function(k){return w[k.Ga]},"%b":function(k){return z[k.sa].substring(0,3)},"%B":function(k){return z[k.sa]},"%C":function(k){return g((k.X+1900)/100|0,2)},"%d":function(k){return g(k.za,2)},"%e":function(k){return f(k.za,2," ")},"%g":function(k){return p(k).toString().substring(2)},"%G":function(k){return p(k)},"%H":function(k){return g(k.Fa,
2)},"%I":function(k){k=k.Fa;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.za+hb(gb(k.X+1900)?ib:jb,k.sa-1),3)},"%m":function(k){return g(k.sa+1,2)},"%M":function(k){return g(k.nc,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Fa&&12>k.Fa?"AM":"PM"},"%S":function(k){return g(k.oc,2)},"%t":function(){return"\t"},"%u":function(k){return k.Ga||7},"%U":function(k){var t=new Date(k.X+1900,0,1),v=0===t.getDay()?t:kb(t,7-t.getDay());k=new Date(k.X+1900,k.sa,k.za);return 0>
l(v,k)?g(Math.ceil((31-v.getDate()+(hb(gb(k.getFullYear())?ib:jb,k.getMonth()-1)-31)+k.getDate())/7),2):0===l(v,t)?"01":"00"},"%V":function(k){var t=new Date(k.X+1901,0,4),v=n(new Date(k.X+1900,0,4));t=n(t);var B=kb(new Date(k.X+1900,0,1),k.Ha);return 0>l(B,v)?"53":0>=l(t,B)?"01":g(Math.ceil((v.getFullYear()<k.X+1900?k.Ha+32-v.getDate():k.Ha+1-v.getDate())/7),2)},"%w":function(k){return k.Ga},"%W":function(k){var t=new Date(k.X,0,1),v=1===t.getDay()?t:kb(t,0===t.getDay()?1:7-t.getDay()+1);k=new Date(k.X+
1900,k.sa,k.za);return 0>l(v,k)?g(Math.ceil((31-v.getDate()+(hb(gb(k.getFullYear())?ib:jb,k.getMonth()-1)-31)+k.getDate())/7),2):0===l(v,t)?"01":"00"},"%y":function(k){return(k.X+1900).toString().substring(2)},"%Y":function(k){return k.X+1900},"%z":function(k){k=k.mc;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.pc},"%%":function(){return"%"}};for(r in m)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),m[r](e)));r=Wa(c,!1);if(r.length>
b)return 0;K.set(r,a);return r.length-1}function mb(a){try{a()}catch(b){E(b)}}var Y=0,Z=null,nb=0,ob=[],pb={},qb={},rb=0,sb=null,tb=[],ub=[];function vb(a){var b={},c;for(c in a)(function(e){var f=a[e];b[e]="function"===typeof f?function(){ob.push(e);try{return f.apply(null,arguments)}finally{if(!G){var g=ob.pop();assert(g===e);Z&&1===Y&&0===ob.length&&(Y=0,mb(d._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.Fc(),sb&&(sb(),sb=null))}}}:f})(c);return b}
function wb(){var a=xb(4108),b=a+12;L[a>>2]=b;L[a+4>>2]=b+4096;b=ob[0];var c=pb[b];void 0===c&&(c=rb++,pb[b]=c,qb[c]=b);L[a+8>>2]=c;return a}
function yb(a){if(!G){if(0===Y){var b=!1,c=!1;a(function(e){if(!G&&(nb=e||0,b=!0,c)){Y=2;mb(function(){d._asyncify_start_rewind(Z)});"undefined"!==typeof V&&V.Wa.ob&&V.Wa.resume();var f=(0,d.asm[qb[L[Z+8>>2]]])();Z||(e=tb,tb=[],e.forEach(function(g){g(f)}))}});c=!0;b||(Y=1,Z=wb(),mb(function(){d._asyncify_start_unwind(Z)}),"undefined"!==typeof V&&V.Wa.ob&&V.Wa.pause())}else 2===Y?(Y=0,mb(d._asyncify_stop_rewind),zb(Z),Z=null,ub.forEach(function(e){if(!G)try{e()}catch(f){if(!(f instanceof ma)&&"unwind"!==
f)throw f&&"object"===typeof f&&f.stack&&F("exception thrown: "+[f,f.stack]),f;}})):E("invalid state: "+Y);return nb}}function Ab(a){return yb(function(b){a().then(b)})}function Cb(a,b,c,e){a||(a=this);this.parent=a;this.S=a.S;this.xa=null;this.id=T.$b++;this.name=b;this.mode=c;this.M={};this.O={};this.rdev=e}
Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ub:{get:function(){return T.T(this.mode)}},Ua:{get:function(){return T.Aa(this.mode)}}});T.yb=Cb;T.kc();var V;function Wa(a,b){var c=Array(ua(a)+1);a=ta(a,c,0,c.length);b&&(c.length=a);return c}
var Fb={f:function(a,b,c){bb=c;try{var e=X(a);switch(b){case 0:var f=W();return 0>f?-28:T.open(e.path,e.flags,0,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=W(),e.flags|=f,0;case 12:return f=W(),ya[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return L[Db()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof T&&g instanceof T.L||E(g),-g.V}},h:function(a,b){try{var c=X(a);return ab(c.path,b)}catch(e){return"undefined"!==typeof T&&e instanceof
T.L||E(e),-e.V}},s:function(a,b,c){bb=c;try{var e=X(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var f=W();return L[f>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return f=W(),T.Ta(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:E("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof T&&g instanceof T.L||E(g),-g.V}},k:function(){F("warning: unsupported syscall: __sys_madvise1");
return 0},j:function(a,b,c,e,f,g){try{a:{g<<=12;var l=!1;if(0!==(e&16)&&0!==a%65536)var n=-28;else{if(0!==(e&32)){E();var p=void 0;if(!p){n=-48;break a}l=!0}else{var m=T.ia(f);if(!m){n=-8;break a}var r=T.pa(m,a,b,g,c,e);p=r.fc;l=r.Ja}$a[p]={Wb:p,Vb:b,Ja:l,fd:f,ec:c,flags:e,offset:g};n=p}}return n}catch(w){return"undefined"!==typeof T&&w instanceof T.L||E(w),-w.V}},i:function(a,b){try{var c=$a[a];if(0!==b&&c){if(b===c.Vb){var e=T.ia(c.fd);if(e&&c.ec&2){var f=c.flags,g=c.offset,l=J.slice(a,a+b);T.qa(e,
l,g,b,f)}$a[a]=null;c.Ja&&zb(c.Wb)}var n=0}else n=-28;return n}catch(p){return"undefined"!==typeof T&&p instanceof T.L||E(p),-p.V}},e:function(a,b,c){bb=c;try{var e=sa(a),f=c?W():0;return T.open(e,b,f).fd}catch(g){return"undefined"!==typeof T&&g instanceof T.L||E(g),-g.V}},g:function(a,b){try{return a=sa(a),ab(a,b)}catch(c){return"undefined"!==typeof T&&c instanceof T.L||E(c),-c.V}},b:function(){E()},t:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=cb();else return L[Db()>>2]=28,-1;L[b>>
2]=a/1E3|0;L[b+4>>2]=a%1E3*1E6|0;return 0},l:function(a){noExitRuntime=!1;na=0;Eb(a)},n:function(a,b,c){J.copyWithin(a,b,b+c)},c:function(a){var b=J.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(a,e);0<e%65536&&(e+=65536-e%65536);a:{try{qa.grow(Math.min(2147483648,e)-xa.byteLength+65535>>>16);za();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},o:function(){return Ab(async()=>{var a=await d.queue.get();const b=ua(a)+
1,c=xb(b);ta(a,J,c,b);return c})},v:function(a,b){var c=0;eb().forEach(function(e,f){var g=b+c;f=L[a+4*f>>2]=g;for(g=0;g<e.length;++g)K[f++>>0]=e.charCodeAt(g);K[f>>0]=0;c+=e.length+1});return 0},w:function(a,b){var c=eb();L[a>>2]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});L[b>>2]=e;return 0},a:function(a){Eb(a)},d:function(a){try{var b=X(a);T.close(b);return 0}catch(c){return"undefined"!==typeof T&&c instanceof T.L||E(c),c.V}},u:function(a,b){try{var c=X(a);K[b>>0]=c.tty?2:T.T(c.mode)?
3:T.oa(c.mode)?7:4;return 0}catch(e){return"undefined"!==typeof T&&e instanceof T.L||E(e),e.V}},r:function(a,b,c,e){try{a:{for(var f=X(a),g=a=0;g<c;g++){var l=L[b+(8*g+4)>>2],n=T.read(f,K,L[b+8*g>>2],l,void 0);if(0>n){var p=-1;break a}a+=n;if(n<l)break}p=a}L[e>>2]=p;return 0}catch(m){return"undefined"!==typeof T&&m instanceof T.L||E(m),m.V}},m:function(a,b,c,e,f){try{var g=X(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;T.$(g,a,e);P=[g.position>>>0,(O=g.position,
1<=+Math.abs(O)?0<O?(Math.min(+Math.floor(O/4294967296),4294967295)|0)>>>0:~~+Math.ceil((O-+(~~O>>>0))/4294967296)>>>0:0)];L[f>>2]=P[0];L[f+4>>2]=P[1];g.Qa&&0===a&&0===e&&(g.Qa=null);return 0}catch(l){return"undefined"!==typeof T&&l instanceof T.L||E(l),l.V}},q:function(a,b,c,e){try{a:{for(var f=X(a),g=a=0;g<c;g++){var l=T.write(f,K,L[b+8*g>>2],L[b+(8*g+4)>>2],void 0);if(0>l){var n=-1;break a}a+=l}n=a}L[e>>2]=n;return 0}catch(p){return"undefined"!==typeof T&&p instanceof T.L||E(p),p.V}},p:function(a,
b,c,e){return lb(a,b,c,e)}};
(function(){function a(g){g=g.exports;g=vb(g);d.asm=g;qa=d.asm.x;za();Ba.unshift(d.asm.y);Ia()}function b(g){a(g.instance)}function c(g){return Ma().then(function(l){return WebAssembly.instantiate(l,e)}).then(g,function(l){F("failed to asynchronously prepare wasm: "+l);E(l)})}var e={a:Fb};Ha();if(d.instantiateWasm)try{var f=d.instantiateWasm(e,a);return f=vb(f)}catch(g){return F("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return pa||"function"!==typeof WebAssembly.instantiateStreaming||
Ja()||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,e).then(b,function(l){F("wasm streaming compile failed: "+l);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.y).apply(null,arguments)};
var xb=d._malloc=function(){return(xb=d._malloc=d.asm.z).apply(null,arguments)},zb=d._free=function(){return(zb=d._free=d.asm.A).apply(null,arguments)};d._main=function(){return(d._main=d.asm.B).apply(null,arguments)};
var Db=d.___errno_location=function(){return(Db=d.___errno_location=d.asm.C).apply(null,arguments)},wa=d.stackAlloc=function(){return(wa=d.stackAlloc=d.asm.D).apply(null,arguments)},dynCall_vi=d.dynCall_vi=function(){return(dynCall_vi=d.dynCall_vi=d.asm.F).apply(null,arguments)},dynCall_v=d.dynCall_v=function(){return(dynCall_v=d.dynCall_v=d.asm.G).apply(null,arguments)};d._asyncify_start_unwind=function(){return(d._asyncify_start_unwind=d.asm.H).apply(null,arguments)};
d._asyncify_stop_unwind=function(){return(d._asyncify_stop_unwind=d.asm.I).apply(null,arguments)};d._asyncify_start_rewind=function(){return(d._asyncify_start_rewind=d.asm.J).apply(null,arguments)};d._asyncify_stop_rewind=function(){return(d._asyncify_stop_rewind=d.asm.K).apply(null,arguments)};d.FS=T;var Gb;function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ga=function Hb(){Gb||Ib();Gb||(Ga=Hb)};
function Ib(a){function b(){if(!Gb&&(Gb=!0,d.calledRun=!0,!G)){d.noFSInit||T.va.Sa||T.va();T.tb=!1;Na(Ba);Na(Ca);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(Jb){var c=a,e=d._main;c=c||[];var f=c.length+1,g=wa(4*(f+1));L[g>>2]=va(ea);for(var l=1;l<f;l++)L[(g>>2)+l]=va(c[l-1]);L[(g>>2)+f]=0;try{var n=e(f,g);Eb(n)}catch(p){p instanceof ma||"unwind"==p||((c=p)&&"object"===typeof p&&p.stack&&(c=[p,p.stack]),F("exception thrown: "+c),fa(1,p))}finally{}}if(d.postRun)for("function"==typeof d.postRun&&
(d.postRun=[d.postRun]);d.postRun.length;)c=d.postRun.shift(),Da.unshift(c);Na(Da)}}a=a||da;if(!(0<M)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ea();Na(Aa);0<M||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=Ib;function Eb(a){if(!(noExitRuntime||0<na)){if(d.onExit)d.onExit(a);G=!0}fa(a,new ma(a))}if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();
var Jb=!0;d.noInitialRun&&(Jb=!1);Ib();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
